// import './globals.css'
// import './page.module.css'
export const metadata = {
  title: "WallStreet'23",
  description: 'Generated by create next app',
}

import { Montserrat } from "next/font/google";
const montserrat = Montserrat({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
         <div className='flex flex-col'>
        {children}
        </div>
        </body>
    </html>
  )
}
